define(function(g,d){function h(a){var b;this.$form=b=c(a.form);this.$id=b.find(a.id);this.$password=b.find(a.password);this.$remember=b.find(a.remember);this.$submit=b.find(a.submit);this.$submitIng=this.$submit.next();this.$msg=b.find(".msg");this.loginStatus=!0}function i(a){var b;this.$form=b=c(a.form);this.$id=b.find(a.id);this.$mail=b.find(a.mail);this.$password=b.find(a.password);this.$password2=b.find(a.password2);this.$agree=b.find(a.agree);this.$submit=b.find(a.submit);this.$submitIng=this.$submit.next();
this.$msg=b.find(".msg2");this.loginStatus=!0}function j(a){var b;this.$form=b=c(a.form);this.$id=b.find(a.id);this.$submit=b.find(a.submit);this.$submitIng=this.$submit.next();this.$msg=b.find(".msg");this.loginStatus=!0}function k(a){var b;this.$form=b=c(a.form);this.$password=b.find(a.password);this.$password2=b.find(a.password2);this.$submit=b.find(a.submit);this.$msg=b.find(".msg");this.loginStatus=!0}var c=g("jquery"),f=g("global").config;c.extend(h.prototype,{initialize:function(){this.events()},
events:function(){var a=this;a.$submit.on("click",function(b){b.preventDefault();var b=a.$id.val(),e=a.$password.val();a.$remember.prop("checked");b?e?(a.hideError(),a.loginIng(),c("#login-form").trigger("submit")):a.showError("\u8bf7\u8f93\u5165\u5bc6\u7801"):a.showError("\u8bf7\u8f93\u5165\u7528\u6237\u540d")});a.$form.on("keyup",function(b){13==b.keyCode&&a.$submit.trigger("click")})},loginSuc:function(){},loginIng:function(){this.$submitIng.show()},loginEnd:function(){this.$submitIng.hide()},
showError:function(a){this.$msg.fadeIn("quick").text(a)},hideError:function(){this.$msg.fadeOut("quick")}});c.extend(i.prototype,{initialize:function(){this.events()},events:function(){var a=this;a.$mail.on("blur",c.proxy(a.mailBlur,a));a.$id.on("blur",c.proxy(a.idBlur,a));a.$password.on("blur",c.proxy(a.passwordBlur,a));a.$password2.on("blur",c.proxy(a.passwordBlur2,a));a.$agree.on("click",c.proxy(a.agreeClick,a));a.$submit.on("click",c.proxy(a.submit,a));a.$form.on("keyup",function(b){13==b.keyCode&&
a.$submit.trigger("click")})},mailBlur:function(a){a=c(a.target).val();!a||-1==a.search("^([a-zA-Z0-9_.-])+@(([a-zA-Z0-9-])+.)+([a-zA-Z0-9]{2,4})+$")?(this.showError("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u90ae\u7bb1"),this.loginStatus=!1):(this.hideError(),this.loginStatus=!0)},idBlur:function(a){a=c(a.target).val();!a||-1==a.search("[A-Za-z0-9_]{4,20}")?(this.showError("\u7528\u6237\u540d\u4e3a4-20\u4e2a\u5b57\u7b26\uff0c\u4ec5\u5141\u8bb8\u5b57\u6bcd\u3001\u6570\u5b57\u548c\u4e0b\u5212\u7ebf"),
this.loginStatus=!1):(this.hideError(),this.loginStatus=!0)},passwordBlur:function(a){(a=this.password=c(a.target).val())?6>a.length||16<a.length?(this.showError("\u5bc6\u7801\u957f\u5ea6\u4e3a6-16\u4f4d"),this.loginStatus=!1):this.password2&&a!=this.password2?(this.showError("\u4e24\u6b21\u5bc6\u7801\u8f93\u5165\u4e0d\u4e00\u81f4\uff01"),this.loginStatus=!1):(this.hideError(),this.loginStatus=!0):(this.showError("\u8bf7\u8f93\u5165\u5bc6\u7801"),this.loginStatus=!1)},passwordBlur2:function(a){(a=
this.password2=c(a.target).val())?6>a.length||16<a.length?(this.showError("\u5bc6\u7801\u957f\u5ea6\u4e3a6-16"),this.loginStatus=!1):this.password&&a!=this.password?(this.showError("\u4e24\u6b21\u5bc6\u7801\u8f93\u5165\u4e0d\u4e00\u81f4"),this.loginStatus=!1):(this.hideError(),this.loginStatus=!0):(this.showError("\u8bf7\u786e\u8ba4\u5bc6\u7801"),this.loginStatus=!1)},agreeClick:function(a){this.loginStatus=c(a.target).prop("checked")?!0:!1},submit:function(a){a.preventDefault();for(var b=this,a=
[b.$mail,b.$id,b.$password,b.$password2],e=0,d=a.length;e<d;e++)if(a[e].trigger("blur"),!b.loginStatus)return;b.$agree.prop("checked")?(b.hideError(),b.loginIng(),c.ajax({url:f.register,type:"post",data:{}}).done(function(){b.loginEnd()}).fail(function(){b.showError("\u7f51\u7edc\u4f3c\u4e4e\u51fa\u4e86\u95ee\u9898\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5");b.loginEnd()})):b.showError("\u8bf7\u540c\u610f\u6761\u6b3e")},loginSuc:function(){},loginIng:function(){this.$submitIng.show()},loginEnd:function(){this.$submitIng.hide()},
showError:function(a){this.$msg.fadeIn("qucik").text(a)},hideError:function(){this.$msg.fadeOut("qucik")}});c.extend(j.prototype,{initialize:function(){this.events()},events:function(){var a=this;a.$submit.on("click",c.proxy(a.submit,a));a.$form.on("keyup",function(b){13==b.keyCode&&a.$submit.trigger("click")})},idCheck:function(){return!this.$id.val()?(this.showError("\u8bf7\u8f93\u5165\u7528\u6237\u540d"),this.loginStatus=!1):!0},submit:function(a){a.preventDefault();var b=this;b.idCheck()&&(b.hideError(),
b.loginIng(),c.ajax({url:f.reset,type:"post",data:{}}).done(function(){b.loginEnd()}).fail(function(){b.loginEnd()}))},resetSuccess:function(){},loginIng:function(){this.$submitIng.show()},loginEnd:function(){this.$submitIng.hide()},showError:function(a){this.$msg.fadeIn("quick").text(a)},hideError:function(){this.$msg.fadeOut("quick")}});c.extend(k.prototype,{initialize:function(){this.events()},events:function(){var a=this;a.$submit.on("click",c.proxy(a.submit,a));a.$form.on("keyup",function(b){13==
b.keyCode&&a.$submit.trigger("click")})},checkLength:function(){var a=this.$password.val();if(!a)return this.showError("\u8bf7\u8f93\u5165\u5bc6\u7801"),!1;a=a.length;return 6>a||16<a?(this.showError("\u5bc6\u7801\u957f\u5ea6\u4e3a6-16\u4f4d"),!1):!0},checkRepeat:function(){var a=this.$password.val(),b=this.$password2.val();return a!=b?(this.showError("\u4e24\u6b21\u5bc6\u7801\u8f93\u5165\u4e0d\u4e00\u81f4\uff01"),!1):!0},submit:function(a){a.preventDefault();c(a.currentTarget);this.checkLength()&&
this.checkRepeat()&&(this.hideError(),a={password:this.$password.val()},c.ajax({url:f.resetPsw,type:"post",data:a}).done(function(){}).fail(function(){}))},loginSuc:function(){},loginIng:function(){this.$submitIng.show()},loginEnd:function(){this.$submitIng.hide()},showError:function(a){this.$msg.fadeIn("quick").text(a)},hideError:function(){this.$msg.fadeOut("quick")}});d.login=h;d.register=i;d.reset=j;d.resetPwd=k});
