window.Modernizr=function(h,d,y){var j={},n=d.documentElement,q=d.createElement("modernizr"),q=q.style,r={},h=[],o=h.slice,t,w={}.hasOwnProperty,u;"undefined"!==typeof w&&"undefined"!==typeof w.call?u=function(e,f){return w.call(e,f)}:u=function(e,f){return f in e&&"undefined"===typeof e.constructor.prototype[f]};Function.prototype.bind||(Function.prototype.bind=function(e){var f=this;if("function"!=typeof f)throw new TypeError;var d=o.call(arguments,1),j=function(){if(this instanceof j){var s=function(){};
s.prototype=f.prototype;var s=new s,h=f.apply(s,d.concat(o.call(arguments)));return Object(h)===h?h:s}return f.apply(e,d.concat(o.call(arguments)))};return j});for(var p in r)u(r,p)&&(t=p.toLowerCase(),j[t]=r[p](),h.push((j[t]?"":"no-")+t));j.addTest=function(e,f){if("object"==typeof e)for(var d in e)u(e,d)&&j.addTest(d,e[d]);else{e=e.toLowerCase();if(j[e]!==y)return j;f="function"==typeof f?f():f;n.className+=" "+(f?"":"no-")+e;j[e]=f}return j};q.cssText="";return q=null,function(e,f){function d(){var a=
k.elements;return"string"==typeof a?a.split(" "):a}function j(a){var b=w[a[t]];return b||(b={},i++,a[t]=i,w[i]=b),b}function h(a,b,c){b||(b=f);if(v)return b.createElement(a);c||(c=j(b));var g;return c.cache[a]?g=c.cache[a].cloneNode():u.test(a)?g=(c.cache[a]=c.createElem(a)).cloneNode():g=c.createElem(a),g.canHaveChildren&&!q.test(a)?c.frag.appendChild(g):g}function p(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=
function(c){return k.shivMethods?h(c,a,b):b.createElem(c)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/\w+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'})+");return n}")(k,b.frag)}function o(a){a||(a=f);var b=j(a);if(k.shivCSS&&!r&&!b.hasCSS){var c,g=a;c=g.createElement("p");g=g.getElementsByTagName("head")[0]||g.documentElement;c=(c.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",
g.insertBefore(c.lastChild,g.firstChild));b.hasCSS=!!c}return v||p(a,b),a}var n=e.html5||{},q=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,u=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,r,t="_html5shiv",i=0,w={},v;(function(){try{var a=f.createElement("a");a.innerHTML="<xyz></xyz>";r="hidden"in a;var b;if(!(b=1==a.childNodes.length)){f.createElement("a");var c=f.createDocumentFragment();b="undefined"==typeof c.cloneNode||
"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}v=b}catch(g){v=r=!0}})();var k={elements:n.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==n.shivCSS,supportsUnknownElements:v,shivMethods:!1!==n.shivMethods,type:"default",shivDocument:o,createElement:h,createDocumentFragment:function(a,b){a||(a=f);if(v)return a.createDocumentFragment();
for(var b=b||j(a),c=b.frag.cloneNode(),g=0,e=d(),h=e.length;g<h;g++)c.createElement(e[g]);return c}};e.html5=k;o(f)}(this,d),j._version="2.6.2",n.className=n.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+h.join(" ")),j}(this,this.document);
(function(h,d,y){function j(a){return"[object Function]"==z.call(a)}function n(a){return"string"==typeof a}function q(){}function r(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function o(){var a=x.shift();s=1;a?a.t?e(function(){("c"==a.t?k.injectCss:k.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),o()):s=0}function t(a,b,c,g,j,h,l){function I(c){if(!J&&r(m.readyState)&&(n.r=J=1,!s&&o(),m.onload=m.onreadystatechange=null,c)){"img"!=a&&e(function(){H.removeChild(m)},50);for(var g in i[b])i[b].hasOwnProperty(g)&&
i[b][g].onload()}}var l=l||k.errorTimeout,m=d.createElement(a),J=0,B=0,n={t:c,s:b,e:j,a:h,x:l};1===i[b]&&(B=1,i[b]=[]);"object"==a?m.data=b:(m.src=b,m.type=a);m.width=m.height="0";m.onerror=m.onload=m.onreadystatechange=function(){I.call(this,B)};x.splice(g,0,n);"img"!=a&&(B||2===i[b]?(H.insertBefore(m,F?null:f),e(I,l)):i[b].push(m))}function w(a,b,c,g,f){return s=0,b=b||"j",n(a)?t("c"==b?K:E,a,b,this.i++,c,g,f):(x.splice(this.i++,0,a),1==x.length&&o()),this}function u(){var a=k;return a.loader={load:w,
i:0},a}var p=d.documentElement,e=h.setTimeout,f=d.getElementsByTagName("script")[0],z={}.toString,x=[],s=0,C="MozAppearance"in p.style,F=C&&!!d.createRange().compareNode,H=F?p:f.parentNode,p=h.opera&&"[object Opera]"==z.call(h.opera),p=!!d.attachEvent&&!p,E=C?"object":p?"script":"img",K=p?"script":E,G=Array.isArray||function(a){return"[object Array]"==z.call(a)},A=[],i={},D={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},v,k;k=function(a){function b(a){var a=a.split("!"),b=A.length,c=
a.pop(),g=a.length,c={url:c,origUrl:c,prefixes:a},f,e,d;for(e=0;e<g;e++)d=a[e].split("="),(f=D[d.shift()])&&(c=f(c,d));for(e=0;e<b;e++)c=A[e](c);return c}function c(a,c,e,f,g){var d=b(a),h=d.autoCallback;d.url.split(".").pop().split("?").shift();d.bypass||(c&&(c=j(c)?c:c[a]||c[f]||c[a.split("/").pop().split("?")[0]]),d.instead?d.instead(a,c,e,f,g):(i[d.url]?d.noexec=!0:i[d.url]=1,e.load(d.url,d.forceCSS||!d.forceJS&&"css"==d.url.split(".").pop().split("?").shift()?"c":y,d.noexec,d.attrs,d.timeout),
(j(c)||j(h))&&e.load(function(){u();c&&c(d.origUrl,g,f);h&&h(d.origUrl,g,f);i[d.url]=2})))}function g(a,b){function d(a,f){if(a)if(n(a))f||(g=function(){var a=[].slice.call(arguments);h.apply(this,a);l()}),c(a,g,b,0,e);else{if(Object(a)===a)for(i in k=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(i)&&(!f&&!--k&&(j(g)?g=function(){var a=[].slice.call(arguments);h.apply(this,a);l()}:g[i]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);l()}}(h[i])),c(a[i],g,b,i,e))}else!f&&l()}var e=!!a.test,f=a.load||a.both,g=a.callback||q,h=g,l=a.complete||q,k,i;d(e?a.yep:a.nope,!!f);f&&d(f)}var f,e,d=this.yepnope.loader;if(n(a))c(a,0,d,0);else if(G(a))for(f=0;f<a.length;f++)e=a[f],n(e)?c(e,0,d,0):G(e)?k(e):Object(e)===e&&g(e,d);else Object(a)===a&&g(a,d)};k.addPrefix=function(a,b){D[a]=b};k.addFilter=function(a){A.push(a)};k.errorTimeout=1E4;null==d.readyState&&d.addEventListener&&(d.readyState="loading",d.addEventListener("DOMContentLoaded",
v=function(){d.removeEventListener("DOMContentLoaded",v,0);d.readyState="complete"},0));h.yepnope=u();h.yepnope.executeStack=o;h.yepnope.injectJs=function(a,b,c,g,h,j){var l=d.createElement("script"),i,m,g=g||k.errorTimeout;l.src=a;for(m in c)l.setAttribute(m,c[m]);b=j?o:b||q;l.onreadystatechange=l.onload=function(){!i&&r(l.readyState)&&(i=1,b(),l.onload=l.onreadystatechange=null)};e(function(){i||(i=1,b(1))},g);h?l.onload():f.parentNode.insertBefore(l,f)};h.yepnope.injectCss=function(a,b,c,g,h,j){var g=
d.createElement("link"),i,b=j?o:b||q;g.href=a;g.rel="stylesheet";g.type="text/css";for(i in c)g.setAttribute(i,c[i]);h||(f.parentNode.insertBefore(g,f),e(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
